### ISSUE TITLE
Mconf-live development environment

### ISSUE THREAD

**Issue by liyanouou** [mconf-cookbooks/mconf-live-solo#1]
I have already installed mconf-Live. Then I tried to install development environment for Mconf-Live. Is the development environment for Mconf-Live same as BigBlueButton(http://docs.bigbluebutton.org/dev/setup.html)?

**Comment by fcecagno** [comment]
Yes, it's exactly the same.

**Comment by liyanouou** [comment]
The source  for development environment I clone from github(https://github.com/mconf/bigbluebutton) is for BigBlueButton, can it be used to install development environment for Mconf?

I have installed development environment for Mconf following the guide(http://docs.bigbluebutton.org/dev/setup.html), the result appears 404 not found. Should I change something to install the development environment?

**Comment by fcecagno** [comment]
The repository is correct, but you should use a branch different than master. The latest Mconf-Live is on mconf-live0.7.1
When you clone the source code, you can specify "-b mconf-live0.7.1" to get the right branch.

**Comment by liyanouou** [comment]
Thanks a lot
