### ISSUE TITLE
Bigbluebutton cookbook's libreoffice ppa url is outdated

### ISSUE THREAD

**Issue by lfzawacki** [mconf-cookbooks/mconf-live-solo#2]
I had to switch it to uri "ppa:libreoffice/libreoffice-4-4" to make it work.

**Comment by fcecagno** [comment]
It's fixed on https://github.com/mconf-cookbooks/bigbluebutton/blob/master/recipes/default.rb#L42

We just need to update the berksfile lock of the bigbluebutton cookbook and test to make sure it's still working.

**Comment by daronco** [comment]
I upgraded the cookbook to the revisions that just changed the version of libreoffice, tested it and everything's ok. So it's on master now.
