### ISSUE TITLE
Version of Chef and ruby is outdated

### ISSUE THREAD

**Issue by g3rhard** [mconf-cookbooks/mconf-live-solo#3]
Please, update version of Chef and ruby in https://github.com/mconf-cookbooks/mconf-live-solo/blob/master/configure

**Comment by fcecagno** [comment]
Hi @g3rhard , which version do you need for Chef and Ruby?

**Comment by g3rhard** [comment]
Sorry, did not see if you have a description of which version of Ubuntu it fits, and the version of Chef CHEF_VERSION = "12.11.18" is not available in Ubuntu 16.04. Thank you for response.

**Comment by fcecagno** [comment]
Correct, for now Mconf-Live is only compatible with Ubuntu 14.04. When we migrate to Ubuntu 16.04, which should occur in the near future, we'll still be able to install Chef 12.11.18 changing this (https://github.com/mconf-cookbooks/mconf-live-solo/blob/master/configure#L183) to "gem".
